---
# I changed somethin'
name: topiary
description: Topiary aims to be a uniform formatter for simple languages, as part of the Tree-sitter ecosystem.
homepage: https://topiary.tweag.io/
licenses:
  - MIT
languages:
  - nu
categories:
  - Formatter

source:
  id: pkg:cargo/topiary-cli@0.6.1

bin:
  topiary: cargo:topiary
